apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
    team: engineering
---
apiVersion: v1
kind: Namespace
metadata:
  name: qa
  labels:
    name: qa
    team: engineering
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    team: engineering
