apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    team: engineering
---
apiVersion: v1
kind: Namespace
metadata:
  name: qa
  labels:
    team: engineering
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    team: engineering
