apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: myapp
---
apiVersion: v1
kind: Namespace
metadata:
  name: qa
  labels:
    name: myapp
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: myapp
